---
# tasks file for Elastic1
- name: install docker
  apt:
    name: docker.io
    state: latest
    update_cache: yes
  register: docker

- name: install docker.py
  pip:
    name: docker.py
    state: latest
  when: docker.changed

- name: pull elasticsearch image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

- name: create docker network
  docker_network:
    name: elastic

- name: create elasticsearch container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    state: present
    ports:
      - "9200:9200"
      - "9300:9300"
    network:
      - name: elastic

- name: pull logstash image
  docker_image:
    name: docker.elastic.co/logstash/logstash:7.10.1

- name: create logstash container
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.1
    state: present
    ports:
      - "5044:5044"
    network:
      - name: elastic
