---
# tasks file for nagiosmain
  
  name: Download and Extract Nagios Core
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/release/nagios-4.4.5.tar.gz
    dest: /tmp
    copy: no

  name: Configure Nagios within ubuntu
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios-4.4.5


  name: Compile nagios make clear
  make:
    chdir: /tmp/nagios-4.4.5
    target: clean


  name: Compile nagios make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5


  name: Compile nagios make install-init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5


  name: Compile Nagios make install-config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5


  name: Compile Nagios make install-commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5


  name: Fire up the web interface installer
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5


  name: Add user account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: user
    password: password


  name: a2enmod cgi
  command: a2nmod cgi

  
  name: Restart apache2
  service:
    name: apache2
    command: restarted
