---
# tasks file for roles/prometheus
name: add prometheus rpm
copy:
  src: prometheus.repo
  dest: /etc/yum.repos.d/

name: update centos
yum:
  update-cache: yes

name: Install Prometheus and config
become: yes
dnf:
  name:
    - prometheus2
    - node_exporter
