---
# tasks file for centos/nagios
name: installing
yum:
  name:
    - per1
    - gcc
    - glibc
    - glibc-common
    - unzip
    - php
    - gd
    - gd-devel
    - postfix
    - compat-openssl10
  state: present

name: add group for nagios
group:
  name: naggroup
  state: present

name: add user for nagios
user:
  name: naguser
  group: naggroup

name: install angios
unarchive:
  src: https://assets.nagios.com/download/nagioscore/release/nagios-4.4.5.tar.gz
  dest: /tmp
  remote_src: yes

name: config nagios
command: ./configure --with-command-group=naggroup
args:
  chdir: /tmp/nagios-4.4.5

 name: Cleaning
 make:
   target: clean
   chdir: /tmp/nagios-4.4.5

  name: make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

 name: make install init
 become: yes
 make:
   target: install-init
   chdir: /tmp/nagios-4.4.5

 name: make install-webconf
 become: yes
 make:
   target: install-webconf
   chdir: /tmp/nagios-4.4.5

 name: install passlib
 pip:
   name: passlib

 name: create user in nagios
 htpasswd:
   path: /usr/local/nagios/etc/htpasswd.users
   name: user
   password: password

 name: restart httpd
 service:
   name: httpd
   state: restarted
   enabled: yes
